
doc:
	doxygen
	doxysphinx build source build Doxyfile
	sphinx-build source build

git:
	git clone https://github.com/jothepro/doxygen-awesome-css/

dep:
	pip install --quiet --user doxysphinx sphinxcontrib-doxylink
	gem install --quiet --user sass
