extern const pin_obj_t pin_P2;
extern const pin_obj_t pin_P3;
extern const pin_obj_t pin_P4;
extern const pin_obj_t pin_P5;
extern const pin_obj_t pin_P6;
extern const pin_obj_t pin_P7;
extern const pin_obj_t pin_P8;
extern const pin_obj_t pin_P9;
extern const pin_obj_t pin_P10;
extern const pin_obj_t pin_P11;
extern const pin_obj_t pin_P12;
extern const pin_obj_t pin_P13;
extern const pin_obj_t pin_P14;
extern const pin_obj_t pin_P15;
extern const pin_obj_t pin_P16;
extern const pin_obj_t pin_P17;
extern const pin_obj_t pin_P18;
extern const pin_obj_t pin_P19;
extern const pin_obj_t pin_P20;
extern const pin_obj_t pin_P21;
extern const pin_obj_t pin_P22;
extern const pin_obj_t pin_P23;
extern const pin_obj_t pin_P24;
extern const pin_obj_t pin_P25;
extern const pin_obj_t pin_P26;
extern const pin_obj_t pin_P27;
extern const pin_obj_t pin_P28;
extern const pin_obj_t pin_P29;
extern const pin_obj_t pin_P30;
extern const pin_obj_t pin_P31;
extern const pin_obj_t * const pin_adc1[];
extern const pin_obj_t * const pin_adc2[];
extern const pin_obj_t * const pin_adc3[];
